### ISSUE TITLE
Power by USB

### ISSUE THREAD

**Issue by roaldarbol** [KitronikLtd/Kitronik-Pico-Motor-Driver-Board-MicroPython#3]
Hi there! Sorry in advance, I'm sure there's a better place to ask this question, but I can't find it and it isn't mentioned in this guide.

If I power the Pico from a laptop via USB, do I need the 5V input? Or is the power draw safe enough that it won't damage the laptop? Thanks!

**Comment by DaveAtKitronik** [comment]
The Pico will power up fine just from USB, but the motor driving part of the board will not function without power supplied from the power connector.

**Comment by roaldarbol** [comment]
Thanks, appreciate the fast response. 👌
